# Generated by Django 3.2.12 on 2023-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommend',
            field=models.TextField(blank=True, null=True),
        ),
    ]
