# Generated by Django 3.2.12 on 2023-05-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
