# Generated by Django 3.2.12 on 2023-05-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_review_like_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debate',
            new_name='Comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.review'),
            preserve_default=False,
        ),
    ]
